//
// Created by MI T on 2024/8/12.
//

#ifndef UVCCAMERA_CAMERAPARAMETERSTATE_H
#define UVCCAMERA_CAMERAPARAMETERSTATE_H

#endif //UVCCAMERA_CAMERAPARAMETERSTATE_H

#include "libuvc/libuvc.h"

#define AUTO_EXPOSURE  1
#define EXPOSURE  2
#define BRIGHTNESS  3
#define CONTRAST  4
#define GAIN  5
#define SATURATION  6
#define ZOOM  7
#define ORIENTATION  8

#define DEFAULT_PREVIEW_WIDTH 640
#define DEFAULT_PREVIEW_HEIGHT 480
#define DEFAULT_PREVIEW_FPS 30
#define DEFAULT_PREVIEW_MODE UVC_FRAME_FORMAT_YUYV
