[versions]
activityKtx = "1.10.1"
annotation = "1.9.1"
minSdk = "21"
compileSdk = "35"
targetSdk = "35"
rxjava = "2.2.19"
rxandroid = "2.1.1"
jvm-version = "17"

android-gradle-plugin = "8.8.2"
ksp = "2.1.0-1.0.29"
kotlin = "2.1.0"
coreKtx = "1.16.0"
lifecycle-process = "2.9.0"

appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.2.1"
navigatuion-version = "2.9.0"
coroutines-android = "1.10.2"
gson = "2.13.0"
datastore-preferences = "1.1.7"

work-runtime-ktx = "2.10.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.5.1"
[libraries]
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle-process" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigatuion-version" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigatuion-version" }

coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines-android" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }

work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-lib = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

