[versions]
# sdk版本控制
minSdk = "23"
compileSdk = "36"
targetSdk = "36"

# kt,gradle版本控制
agp = "8.13.0"
kotlin = "2.2.20"
ksp = "2.2.20-2.0.4"

gson = "2.13.0"

appcompat = "1.7.1"
material = "1.12.0"
constraintlayout = "2.2.1"
coreKtx = "1.16.0" # core依赖库
navigatuion-version = "2.9.0" # 路由导航

coroutines-android = "1.10.2" # 协程
activity-ktx = "1.10.1" # activity
fragment-ktx = "1.8.8" # fragment

# 包版本
lifecycle-process = "2.9.1" # 生命周期监听管理


glide = "5.0.7" # 图片框架

okio = "3.17.0" # okio版本

# 单元测试依赖
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
maven-publish = "0.35.0"
[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle-process" }

activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigatuion-version" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigatuion-version" }

coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines-android" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
glide-okhttp = { group = "com.github.bumptech.glide", name = "okhttp3-integration", version.ref = "glide" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-lib = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
