plugins {
    alias(libs.plugins.android.lib)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.maven.publish)
}

android {
    namespace 'com.rain.uvc'
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk  libs.versions.minSdk.get().toInteger()

        ndkVersion "29.0.13113456"
        consumerProguardFiles "consumer-rules.pro"
        ndk{
            abiFilters "arm64-v8a","armeabi-v7a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    externalNativeBuild{
        cmake{
            path = "src/main/cpp/CMakeLists.txt"
            version = "4.1.2"
        }
    }
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates(
            "io.github.yfograin",
            "uvc",
            "1.0.0"
    )

    pom {
        name = "UsbCameraLib"
        description = "Android USB UVC camera library"
        inceptionYear = "2026"
        url = "https://github.com/YFogRain/UsbCameraLib"

        licenses {
            license {
                // 按项目实际许可证填写，不要直接照抄
                name = "The Apache License, Version 2.0"
                url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "repo"
            }
        }

        developers {
            developer {
                id = "YFogRain"
                name = "YFogRain"
                url = "https://github.com/YFogRain"
            }
        }

        scm {
            url = "https://github.com/YFogRain/UsbCameraLib"
            connection = "scm:git:https://github.com/YFogRain/UsbCameraLib.git"
            developerConnection = "scm:git:ssh://git@github.com/YFogRain/UsbCameraLib.git"
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.coroutines.android
}